= Profession de foi
Tepex <tepex@mail.ru>
1.0, 21/V-2025
:source-highliter: rouge

В данном документе я постарался выразить базовые принципы и подходы, которых я придерживаюсь при проектировании и разработке ПО и которые сформировались из моего опыта. Не все из них носят непреложный характер и могут допускать обоснованные отклонения в зависимости от логики обстоятельств и диалектического подхода.

== Архитектура
- DDD (Domain-Driven-Design).
- Clean Architecture.
- Создание DSL для доменов.

Эти парадигмы позволяют создавать формальные системы для домена со своей аксиоматикой, что значительно облегчает
разработку и тестирование бизнес-логики.

Касательно Android:

- MVI, Compose для presentation и UI слоев. Эти технологии, являясь конечными автоматами (Finite-state machine),
позволяют значительно облегчить тестирование UI-логики через Unit-тесты.
- Бинарная мультимодульность для проектов со значительным количеством фичей. Выделение фича-модулей в отдельные независимые подпроекты (Gradle, Git)
со своими артефактами (jar, aar) и жизненными циклами разработки с последующей сборкой в итоговое приложение (apk, bundle)

== Кодовая база
- Борьба с «Primitive Obsession».
- Широкое применение подходов функционального программирования.
- Кодогенерация рутинного кода.
- Принципы SOLID.
- Принцип High Cohesion & Low Coupling.
- Покрытие тестами бизнес-логики.
- Читаемость и поддерживаемость кода как правило важнее оптимизации.
[quote,Robert C. Martin]
“Indeed, the ratio of time spent reading versus writing is well over 10 to 1. We are constantly reading old code as part of the effort to write new code. …[Therefore,] making it easy to read makes it easier to write.”

== Процесс разработки
- Автоматизация жизненного цикла производства ПО, прежде всего за счет CI/CD и создания и конфигурации инфраструктуры (Git, репозиторий артефактов,  сервера сборки).
- Формализация комитов по принципу https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits].
- https://trunkbaseddevelopment.com/[Trunk Based Development] и https://martinfowler.com/articles/feature-toggles.html[Feature Flags].
- Architecture as Code
- Configuration as Code
- Documentation as Code

== Менеджмент
- Уставные положения для команды/проекта. Регламенты написания кода, порядок работ, Code Review, правила именования,
Code Style, роли и их зоны ответственности, должностные инструкции и т.п. — это обязательное начало любой организации.
- Невмешательство. Заказчик/менеджер может сказать «что» надо сделать, но не «как». Вопросы реализации, декомпозиции задач,
пути решений (R&D) решаются среди ролей, непосредственно занятых разработкой и обладающих соответствующими компетенциями
(архитекторы, тим-лиды, сеньоры).
- Санитарные дни. Запланированное время на рефакторинг кода, рефлексию, документирование, самообразование и т.п. Т.к.
любая человеческая деятельность сопровождается издержками производства и отходами, то игнорирование (откладывание) этих
мероприятий закономерно приводит проект к неминуемой гибели и кадровым проблемам.
- Legacy, Time to Market и чистота кода. Противоречие решается путем жесткого разделения проекта на «чистую»
(то, что пойдет в прод) и «грязную» (Proof of Concept, R&D, Legacy) части. Смешение недопустимо.
