= Kotlin DDD Framework (KDDD)
Tepex <tepex@mail.ru>
1.0, 11/IV-2025
:source-highliter: rouge

Фреймворк для проектирования и генерации DDD-моделей на языке Котлин. На текущий момент зтот проект находится в состоянии Prove of Concept и предназначен для демонстрации; будет должным образом оформлен и опубликован в https://central.sonatype.com[Maven Central].

== Причины появления проекта
Применение прогрессивных парадигм и концепций в разработке ПО, таких как [Clean Architecture], [DDD], [DSL], [Функциональное программирование], заветов https://martinfowler.com[Мартина Фаулера] и http://cleancoder.com/products[Роберта Мартина] и др., дает неоспоримое преимущество и выводит разработку ПО на новый технологический уровень, позволяя существенно повысить адаптивность ПО, скорость его разработки, снизить количество багов. Кроме того для больших систем важно обеспечить модульность и соблюдение принципа `Low Coupling & High Cohesion`. Однако практическая реализация этих подходов сопровождается необходимостью соблюдения строгих правил и написания большого количества boilerplate-кода. Особенную боль доставляет рефакторинг кодовой базы при концептуальных изменениях в доменной модели.

Данный проект призван решить эти проблемы за счет предоставления фреймворка для проектирования доменных моделей по канонам DDD и кодогенерации реализаций концептуальных моделей.




== Возможности
* Кодогенерация имплементаций DDD-моделей `Entity`, `Value Object`, заданных с помощью интерфейсов.
* Проектирование DDD-моделей с запрещением `Primitive Obsession`.
* Встроенная валидация моделей.
* Генерация DSL.
* Генерация JSON-сериализатора.
* Потенциальная возможность генерации кода для других систем сериализации/маршаллинга, таких как https://developer.android.com/reference/android/os/Parcelable[Parcelable], https://developer.android.com/training/data-storage/room?hl=en[Room] и т.п.
* Написание бизнес-лоники (`Use Case`) и покрытие тестами сразу после проектирования интерфейса модели.

ыаыв
ыв

== Как работает фреймворк

== Структура проекта
ываыа фыввфы

== Как пользоваться

== Используемые фреймворки
KDDD базируется на двух основных фреймворках:

* https://kotlinlang.org/docs/ksp-overview.html[Kotlin Symbol Processing] для парсинга моделей;
* https://square.github.io/kotlinpoet/[KotlinPoet] для генерации Котлин-кода как результата работы фреймворка.

Дополнительно для JSON-сериализации используется https://square.github.io/kotlinpoet/[Kotlin Serialization]. Используемые зависимости и их версии находятся в link:gradle/libs.versions.toml[Version Catalog]

== Благодарности



