= Примеры различных кейсов FDD
Tepex <tepex79@gmail.com>
1.0, 9/IX-2025
:source-highliter: rouge

В данной директории представлены реализации
различных примеров предметных областей,
бизнес-процессов и сценариев 
использования (Use Cases) на языке 
Котлин с целью демонстрации применения DDD,
https://github.com/graninas/functional-declarative-design-methodology?tab=readme-ov-file[FDD],
функционального программирования, 
Free Monad, eDSL и пр. Скрипты носят
упрощённый характер и запускаются в
https://play.kotlinlang.org[Kotlin Playground].

== Введение
Обозначенные в преамбуле парадигмы и 
подходы призваны упростить разработку,
обеспечить гибкость проектируемой системы, 
снизить стоимость владения. Это 
достигается, в основном, путем увеличения 
уровня абстракции и четкого разделения
на сферы «Что?» и «Как?» — разделить декларацию
и интерпретацию.

Цель данных примеров — показать, как
на концептуальном уровне (уровне абстракций) 
можно и нужно писать и тестировать бизнес-логику.

Реальные проекты должны быть модульными 
с разделением на абстракции

== Общие принципы

== Сэндвич

== Из https://t.me/iDDDqd[DDDevotion chat]
