= Примеры различных кейсов FDD
Tepex <tepex79@gmail.com>
1.0, 9/IX-2025
:source-highliter: rouge
:table-caption!:

В данной директории представлены реализации различных примеров _предметных областей_ (доменов),
_бизнес-процессов_ (БП) и _сценариев использования_ (Use Cases) на языке программирования (ЯП) Котлин с целью демонстрации применения DDD,
https://github.com/graninas/functional-declarative-design-methodology?tab=readme-ov-file[FDD],
функционального программирования (ФП), Free Monad, eDSL и пр. Скрипты носят упрощённый, демонстрационный характер и запускаются в
https://play.kotlinlang.org[Kotlin Playground].

== Введение
Обозначенные в преамбуле парадигмы и подходы призваны упростить разработку, обеспечить гибкость проектируемой системы, снизить стоимость владения. Это 
достигается, в основном, путем увеличения уровня абстракции и четкого разделения на сферы «Что?» и «Как?» — разделить декларацию
и интерпретацию.

*Цель* данных примеров — показать, как на концептуальном уровне (уровне абстракций) можно и нужно писать и тестировать _бизнес-логику_ (БЛ) с помощью специально созданного eDSL средствами ЯП Котлин.

Полагается, что разработка _доменных моделей_ и БЛ находится в компетенции роли _бизнес-аналитика_ (БА) или подобной роли, принятой на конкретном производстве. Такая роль не подразумевает навыки программирования, но при этом  должна выполняться трансляция собранных _бизнес-требований_ (БТ) и других результатов деятельности БА — артефактов, концептуальных моделей в виде абстракций — в код. Такая трансляция может осуществляться автоматически путем кодогенерации (с.м. корень этого репозитория).

Таким образом ставится задача написать примеры 

Такой eDSL призван быть приближен к человекоподобному 

Реальные проекты должны быть модульными с разделением на модули абстракций (`api`) и имплементаций (`impl`).

Kotlin не является полноценным функциональным языком программирования и 

== Общие положения и принципы
БП/БТ/UC/ФТ/

== Предметные области
=== Приготовление сэндвича
*Источник*: https://github.com/graninas/functional-declarative-design-methodology?tab=readme-ov-file[Functional Declarative Design: A Comprehensive Methodology for Statically-Typed Functional Programming Languages] +
*Объект*: сэндвич. +
*Субъект*: сэндвич-машина.

==== Бизнес-требования
Представлены в источнике на диаграмме 1.3, которую можно выразить следующим текстом:

Структура `рецепта` `сэндвича` состоит из 3-х последовательных составляющих (`компонентов` (`components`), ресурсов):

. `Основа` (`bottom`). Тип: `хлеб` (`bread`). Количество: 1.
. `Тело` (`body`). Тип: `компонент` (`component`). Количество: 1 и более.
. `Верхушка` (`top`). Тип: `хлеб` (`bread`). Количество: 0 или 1.

Ресурсы представляются двумя типами:

. `хлеб` (`bread`) может быть следующим:
[arabic]
.. `тост` (`toast`), 
.. `багет` (`baguette`);
. `компонент` (`component`) может быть следующим:
[arabic]
.. `сыр` (`cheese`), 
.. `помидор` (`tomato`),
.. `соль` (`salt`).

NOTE: Слова, выделенные `обратными одинарными кавычками`, составляют _ubiquitous language_ данной _предметной области_ (_домена_) и соответствующими именованиями в коде.

==== Технология
.Технологическая карта
|===
|Этап |Операция |Кол-во

|Начало
|Взять хлеб для основы. Взять и добавить компонент.
|1

|Компоновка тела
|Взять и добавить компонент.
|1-*

|Завершение
|Взять хлеб для верхушки.
|0-1
|===

Производственная цепочка (рецепт):
[arabic]
. 

=== Из https://t.me/iDDDqd[DDDevotion chat]
