/**
 * Портирование на Котлин примера из статьи
 * https://github.com/graninas/functional-declarative-design-methodology?tab=readme-ov-file
 *
 * https://pl.kotl.in/ki9TpN0nd
 * @version 1.0.0
 * @author Tepex
 */

// ***************************************************
// Layer 1. Interfaces (Hierarchical Free Monad eDSLs)
// ***************************************************

// -------------------
// Модуль `api`. eDSL

/** Ресурсы */
sealed interface Ingredient {
    enum class Bread : Ingredient {
        BAGUETTE, TOAST
    }
    
    enum class Component : Ingredient {
        SALT, TOMATO, CHEESE 
    }
}

/** Объект предметной области. ADT, Monad */
sealed interface Sandwich {
    val bottom: Ingredient.Bread
    val components: List<Ingredient.Component>
    
    @ConsistentCopyVisibility
    data class Body private constructor(
        override val bottom: Ingredient.Bread,
        override val components: List<Ingredient.Component>
    ) : Sandwich {
        
        class Builder {
            var bottom: Ingredient.Bread? = null
            var components: List<Ingredient.Component> = emptyList()
            
            fun build(): Body {
                requireNotNull(bottom) { "`bottom` must be initialized!" }
                require(components.isNotEmpty()) { "`components` must not be empty!" }
                return Body(bottom!!, components)
            }
        }
        
        operator fun plus(component: Ingredient.Component): Body =
            copy(components = components + component)
    }
    
    @ConsistentCopyVisibility
    data class Ready private constructor(
        val body: Body,
        val top: Ingredient.Bread?
    ) : Sandwich by body { // Вместо наследования применяется композиция (Composition over inheritance)
        
        class Builder {
            var body: Body? = null
            var top: Ingredient.Bread? = null
            
            fun build(): Ready {
                requireNotNull(body) { "`body` must be initialized!" }
                return Ready(body!!, top)
            }
        }
    }
}

/** `pure` for Sandwich.Body */
fun sandwichBody(block: Sandwich.Body.Builder.() -> Unit): Sandwich.Body =
    Sandwich.Body.Builder().apply { block () }.build()

/** `pure` for Sandwich.Ready */
fun sandwichReady(block: Sandwich.Ready.Builder.() -> Unit): Sandwich.Ready =
    Sandwich.Ready.Builder().apply { block () }.build()
    
/** bind/flatMap */
infix fun Sandwich.Body.next(op: (Sandwich.Body) -> Sandwich.Body): Sandwich.Body =
    op(this)
    
/** bind/flatMap */
infix fun Sandwich.Body.finish(op: (Sandwich.Body) -> Sandwich.Ready): Sandwich.Ready =
    op(this)

/** Технология производства сэндвича */
interface SandwichTechnology {
    val `start new sandwich`: Op.StartNewSandwich
    val `add component`: Op.AddComponent
    val `finish sandwich`: Op.FinishSandwich
    
    /**
     * Технологические операции.
     * 
     * Interpretable Free monadic interfaces.
     */
    sealed interface Op {
        fun interface StartNewSandwich : Op {
            operator fun invoke(bottom: Ingredient.Bread, component: Ingredient.Component): Sandwich.Body
        }
    
        fun interface AddComponent : Op {
            operator fun invoke(sandwich: Sandwich.Body, component: Ingredient.Component): Sandwich.Body
        }
    
        fun interface FinishSandwich : Op {
            operator fun invoke(sandwich: Sandwich.Body, top: Ingredient.Bread?): Sandwich.Ready
        }
    }
}


// ********************************
// Layer 2. Domain & Business Logic
// ********************************

// Рецепты. Можно создать библиотеку рецептов.

/* Рецепт моего сэндвича: 
 * 1. Начало: взять вид хлеба тост и компонент помидор как основу.
 * 2. Добавить сыр
 * 3. Добавить соль
 * 4. Завершение: сверху хлеб не добавлять.
 * 
 * Скрипт (Use Case) на созданном в Layer 1 eDSL.
 * Бизнес-логика пишется только на абстракциях из Layer 1.
 */
fun SandwichTechnology.myRecipe(): Sandwich.Ready = 
    `start new sandwich`(Ingredient.Bread.TOAST, Ingredient.Component.TOMATO) next
    { `add component`(it, Ingredient.Component.CHEESE) } next
    { `add component`(it, Ingredient.Component.SALT) } finish 
    { `finish sandwich`(it, null) }


// *********************************
// Layer 3. Implementation & Runtime
// *******************************

// --------------------------------------
// Модуль `impl`. Имплементации. Runtime.

/**
 *  Autogenerated 
 */
@ConsistentCopyVisibility
data class SandwichTechnologyImpl private constructor(
    override val `start new sandwich`: SandwichTechnology.Op.StartNewSandwich,
    override val `add component`: SandwichTechnology.Op.AddComponent,
    override val `finish sandwich`: SandwichTechnology.Op.FinishSandwich
) : SandwichTechnology {
    
    class Builder {
        var startNewSandwich: ((Ingredient.Bread, Ingredient.Component) -> Sandwich.Body)? = null
        var addComponent: ((Sandwich.Body, Ingredient.Component) -> Sandwich.Body)? = null
        var finishSandwich: ((Sandwich.Body, Ingredient.Bread?) -> Sandwich.Ready)? = null
        fun build(): SandwichTechnology {
            requireNotNull(startNewSandwich) { "`startNewSandwich` must be initialized!" }
            requireNotNull(addComponent) { "`addComponent` must be initialized!" }
            requireNotNull(finishSandwich) { "`finishSandwich` must be initialized!" }
            return SandwichTechnologyImpl(startNewSandwich!!, addComponent!!, finishSandwich!!)
        }
    }
}

fun sandwichTechnology(block: SandwichTechnologyImpl.Builder.() -> Unit): SandwichTechnology =
    SandwichTechnologyImpl.Builder().apply { block() }.build()


// ----------------------
// Модуль `app`. Runtime.
    
/** Нормальная интерпретация */
fun realInterpreter(): SandwichTechnology =
    sandwichTechnology {
        startNewSandwich = { bread, component -> 
            sandwichBody {
                bottom = bread
                components += component
            }
        }
        addComponent = { body, component -> body + component }
        finishSandwich = { _body, _top -> 
            sandwichReady {
                body = _body
                top = _top
            }
        }  
    }
    
fun crazyInterpreter(): SandwichTechnology =
    sandwichTechnology {
        startNewSandwich = { bread, component -> 
            sandwichBody {
                bottom = bread
                components += component
            }
        }
        addComponent = { body, component -> body + component }
        finishSandwich = { _body, _top -> 
            sandwichReady {
                body = _body
                top = _top
            }
        }  
    }
    
fun main() {
    realInterpreter()
        .myRecipe()
        .also { println("sandwich: $it") }
}
