= Правила оформления документации
Tepex <tepex@mail.ru>
1.0, 9/VI-2025
:toc:
:toc-title: Содержание

В данном документе сформулированы правила ведения документации по проекту.

== Общие положения
* Документация представляется различными видами документов, которые определяют их формат.
* Документация ведется в формате https://docs.asciidoctor.org/[Asciidoc]. Формат _Asciidoc_ более функционален по сравнению с _Markdown_, обеспечен средствами конвертации в другие форматы (html, pdf), плагинами для браузеров и IDE, поддерживается системами GitHub, GitLab.
* https://docs.asciidoctor.org/asciidoc/latest/document/header/[Заголовок документа] должен содержать элементы:
** название документа (титул),
** информация об авторе,
** информация о версии и времени документа,
** прочие атрибуты заголовка, необходимые для формирования и рендеринга документа.
* Аннотация. Преамбула, шапка. Краткое изложение в 2-3 предложениях сути документа, о чем он. Дополнительно может содержать описание (или ссылки) легенд, условных обозначений, аббревиатур, используемых в данном документе. Следует сразу после заголовка документа, отделенного пустой строкой.
* Понятия, термины и определения выделяются жирным шрифтом и в виде ссылки на описание (внешней или внутренней).
* Слова и выражения, относящиеся к коду, выделяются `обратными кавычками`.
* Кодовые блоки оформляются согласно https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/[формату Asciidoc].

== Виды документов
Виды документов разделяются на два типа:

. <<#activity,Динамический документ>>, описывающий деятельность, проект. Изменяется во времени согласно его ЖЦ.
. <<#artifact,Статический документ>>, как результат деятельности. Артефакт.

[#activity]
=== Описание деятельности, проекта
Общий шаблон документа формируется на основе определения http://methodolog.ru/books/met_sl.htm#%D0%94%D0%95%D0%AF%D0%A2%D0%95%D0%9B%D0%AC%D0%9D%D0%9E%D0%A1%D0%A2%D0%AC[Деятельности] и должен включать в себя следующие разделы:

. Потребность/Мотивация. Может быть оформлен как один или два раздела. Раздел «Потребность» отвечает на вопрос: «Когда?». Исторически-временной аспект. «Мотивация» отвечает на вопросы: «Где?, Почему?, Зачем?» возникает объект деятельности.
. Цель. Отвечает на вопросы:
. Внешняя среда. Условия, требования, нормы, принципы.
. Задачи.
. Технологии.
. Результат.
. Оценка. Критерии оценки.

[#artifact]
=== Артефакт
Итоговый документ как результат деятельности, проекта. Должен быть хорошо структурирован и размечен якорями для внешних ссылок на фрагменты документа. Как привило имеет сопутствующий <<activity,динамический документ>>, описывающий его создание.

=== README

