= Проектирование и кодогенерация DDD-моделей на Котлин
Tepex <tepex@mail.ru>
1.0, 21/VI-2025

В статье рассматривается разработка доменных моделей в соответствии с тактическими паттернами DDD — `Value Object` и `Entity`, с целью создания собственной строгой иерархии функциональной системы типов (ФСТ). Предложен фреймворк, включающий методологию проектирования и кодогенерации доменных моделей на языке Котлин. Рассматриваются вопросы и ставятся задачи ... организации, планирования, документирования, моделирования, регулирования, управления, оценка результата [Д] как код (DSL).
// научная основа
Разработка фреймворка ведется в значительной части на основе научных работ Д.А. Новикова по организации, управлению и методологии деятельности, приведенных в конце статьи. Используемые понятия, термины и определения основаны на [5] и выделяются *полужирным шрифтом*. Общие термины и понятия, которые легко ищутся в поисковых системах, выделяются _курсивом_. Слова, относящиеся к кодовой базе, выделяются `обратными кавычками`.

== Введение
[quote,Закон Е. А. Седова]
В сложной иерархически организованной системе рост разнообразия на верхнем уровне обеспечивается ограничением разнообразия на предыдущих уровнях, и наоборот, рост разнообразия на нижнем уровне разрушает верхний уровень организации (то есть, система как таковая гибнет).

// Goood practice
В парадигме DDD доменному слою отводится наиважнейшая роль и по этому проектирование и реализация доменных моделей нуждается в особой тщательности и строгости. Применение прогрессивных парадигм и концепций в разработке ПО, таких как _SOLID_, https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html[Clean Architecture], https://en.wikipedia.org/wiki/Domain-driven_design[DDD], https://en.wikipedia.org/wiki/Domain-specific_language[DSL], https://en.wikipedia.org/wiki/Functional_programming[Функциональное программирование], заветов https://martinfowler.com[Мартина Фаулера], http://cleancoder.com/products[Роберта Мартина] и др., дает неоспоримое преимущество и выводит разработку ПО на новый технологический уровень, позволяя существенно повысить адаптивность ПО, скорость его разработки, снизить количество багов. Важно обеспечить модульность, соблюдение принципа _Low Coupling & High Cohesion_, недопускать _Primitive Obsession_.

В условиях непредсказуемости и изменчивости внешней среды, потребностей пользователей, конкурентной борьбы, выживаемость ИТ-проектов определяется способностью к быстрой адаптации. Именно за это отвечает _Core Domain_. Для этого код и процесс его написания должны обладать следующими характеристиками и свойствами:

* Чистый, хорошо структурированный, читаемый код. Есть эмпирическое положение, что 90% времени разработчики тратят на чтение кода. Зачастую — своего собственного. Первоисточник этого утверждения найти не удалось, но оно согласуется с законом Парето и личным опытом. Причин этому множество: это и тезис создателя Perl Ларри Уолла: https://wiki.c2.com/?ProgrammingPerl["We will encourage you to develop the three great virtues of a programmer: laziness, impatience, and hubris."], внешнее давление — дедлайны, _TTM_, иллюзия менеджмента, что _Proof of Concept_ можно выпускать в прод, низкий технологический уровень производства ПО, и т.д.
* Документирование кода с кросс-ссылками на _базу знаний_ проекта.
* Покрытие юнит-тестами.
* Разделение труда, распределенное по ролям. Упорядочивание деятельности с выделением фазы проектирования, стадий и этапов (С.м. [4], стр. 255).
* Разделение на абстракцию и имплементацию со своими жизненными циклами разработки и релиза. Хорошо организованное API.

В целях краткости изложения вводятся понятия <<agent,Агент>> — субъект, пользователь представленного фреймворка. В качестве Агента может выступать как индивид, команда разработки, ИТ-отдел, ИТ-компания или информационные системы такие, как _ИИ-агенты_. <<helix-model,УМ (Улиточная Модель)>> — разрабатываемая Агентом доменная модель его *предметной области* на основе представленного фреймворка. Название «улиточная» обусловлено фрактальным, вихревым, рекурсивным характером структуры моделей.
// Боль и PR


// Предмет

// Что дает?

// Структура изложения
Статья, хоть и имеет весьма узкую, специфическую тему, предназначена не только для разработчиков на Котлин, практикующих DDD, но и для аналитиков, руководителей и владельцев проектов.

* User Story
* Мотивация
* Постановка цели
* Определение задач
* Реализация абстракции:
* ФСТ, k3dm
* Функционал
* Регламент концепций
* Реализация имплементации
* Билдеры: основной, DSL, JSON

* Примеры
* Выводы
* Текущее состояние

== Тело статьи
Обозначенные выше положения вызвали появление идеи создания фреймворка для разработки доменных моделей, выработке методологии и технологии, что позволяет значительно сократить расходы на производство ПО за счет организации и автоматизации деятельности и, тем самым, сведения ее к регулярному виду. Идея породила формирование потребностей, которые можно выразить в виде следующих пользовательских историй (User Story).

=== Пользовательские истории

|===
|Как разработчик я хочу |чтобы

|Иметь ограничения в виде требований, норм, принципов
|в результате получать чистый код и, тем самым, снизить цену владения.

|Иметь базовое основание ФСТ
|проектировать собственную <<helix-model,УМ>>.

|Создавать концептуальные доменные модели в виде собственной строгой иерархии ФСТ и компилируемого кода
|писать функционал (бизнес-логику) в парадигме ФП и тестировать их юнит-тестами на самой ранней стадии.

|Иметь механизм валидации при создании объектов доменных моделей
|реализовывать бизнес-логику.

|Автоматически генерировать код имплементации концептульных моделей, включающий DSL и сериализацию/десериализацию
|сократить затраты на ручной труд, обеспечить гибкость и адаптивность моделей к изменениям внешней среды.
|===

=== Мотивация
Котлин, являясь языком со строгой типизацией с одной строны, является языком общего назначения для самого широкого применения. С другой стороны, такая широта открывает возможности для написания смердящего (_code smell_), опасного и запутанного (_spaghetti code_) кода, превращая кодовую базу в _Big Ball of Mud_. В таком коде имеет место:

* нарушение принципов _SOLID_,
* нарушение инкапсуляции, мутабельность свойств и объектов,
* _Primitive Obsession_ — прямое использование встроенных примитивных типов (`String`, `Int`, `Boolean`, и т.д.) и типов общего назначения (`File`, `Url`, `UUID`, и т.п.),
* отсутствие разделения на абстракцию и имплементацию.

Эти порочные практики во многом обусловлены желанием «срезать угол» из-за значительных трудозатрат (рутинного ручного труда) по их недопущению. Предлагаемый фреймворк позволяет избежать этого.


=== Цель
Создание фреймворка, который включает методологию разработки <<helix-model,УМ>> и инструмент кодогенерации.

=== Задачи

* Создать библиотеку базовой <<fts,ФСТ>> для тактических DDD-паттернов _Entity_ и _Value Object_.
* Разработать методологию и регламент проектирования <<helix-model,УМ>>.
* Разрабртать кодогенератор финального кода, включающего следующий функционал:
** опции кодогенератора, позволяющие настраивать различные правила формирования выходного результата: имена классов, имена пакетов, и пр.,
** кодогенерация:
*** имплементирующих классов,
*** классических билдеров (паттерн _Строитель_),
*** DSL-билдеров,
*** сериализации/десериализации

=== Технологии


== Реализация

=== Нормативная
TODO: Регламент построения интерфейсов

=== Техническая
TODO: Описание работы KSP, KotlinPoet, Domain, Builder, DslBuilder, Serialization
Samples Point, Use Cases

== Подвал

TODO: сопоставить/разложить в таблицу

== Анализ проблем

=== Боль
//* неэффективное расходование ресурсов (неправильные решения, цена владения)
* добавление нового функционала с каждым разом все труднее (костыли)
* не тот результат (иллюзии)
* нехватка ресурсов — время, кадры (цена владения)
* демотивация команды разработки (костыли, иллюзии)
* Растерянность. Потеря во времени и пространстве (иллюзии).

=== Страх
Порождают неадекватные решения

* Боль. Наступить на грабли.
* Неизвестность. Негативный опыт. Молоко-вода.
* Быть обманутым. Риски. Принять неправильное решение. Рождает карго-культ.
* Недостичь результата / получить не тот.
* Сроки

=== Причины
* Кустарщина (неадекватность технологии - некомпетентность)
* высокая цена владения кодовой базы (костыли)
* PoC в проде и необходимость его поддерживать (неправильные решения)
* Иллюзии. Очковтирательство. Потеря управления — нет учета и контроля реальности
* Карго-культ (неправильные решения)


=== Рекомендации

=== Сообщество
// Начальный уровень
// Устав
// Обозначить переход на следующий уровень.

[glossary]
== Понятия, термины и определения
[#agent]
Агент:: Субъект разработки <<helix-model,*УМ*>>. Роль (аналитик, архитектор, разработчик), *ОТС* (в терминологии [1] стр. 12), ИИ-агент.
[#helix-model]
УМ:: Улиточная модель (Helix Model). Доменная модель предметной области <<agent,*Агента*>> в рамках <<fts,*ФСТ*>> и в парадигме тактических _DDD_-паттернов _Value Object_ и _Entity_.
[#fts]
ФСТ:: Формальная система типов (Formal Type System).


== Список источников и литературы
. http://methodolog.ru/books/mkd.pdf[Белов М.В., Новиков Д.А. Методология комплексной деятельности. М.: ЛЕНАНД, 2018].
. http://methodolog.ru/books/md.pdf[Белов М.В., Новиков Д.А. Модели деятельности: основы математической теории деятельности. М.: ЛЕНАНД, 2021].
. Николенко В.Ю. Секреты успешных НИОКР. [б.м.]: Издательские решения, 2023.
. http://methodolog.ru/books/methodology_full.pdf[Новиков А.М., Новиков Д.А. Методология. М.: Синтег, 2007].
. http://methodolog.ru/books/met_sl.pdf[Новиков А.М., Новиков Д.А. Методология: словарь системы основных понятий. М.: Либроком, 2013].
. http://methodolog.ru/books/kiber.pdf[Новиков Д.А. Кибернетика: Навигатор. История кибернетики, современное состояние, перспективы развития. М.: ЛЕНАНД, 2016].
. http://methodolog.ru/books/metod_upr.pdf[Новиков Д.А. Методология управления. М.: Либроком, 2011].
. http://methodolog.ru/books/tyos2005.pdf[Новиков Д.А. Теория управления организационными системами. М.: МПСИ, 2005].
. Ричардс М., Форд Н. Фундаментальный подход к программной архитектуре: паттерны, свойства, проверенные методы. СПб.: Питер, 2023.
. Теория управления. Дополнительные главы. Авторский коллектив под ред. Новикова Д.А. М.: ЛЕНАНД, 2019.
. https://github.com/graninas/functional-declarative-design-methodology?tab=readme-ov-file[Granin. A. Functional Declarative Design: A Comprehensive Methodology for Statically-Typed Functional Programming Languages].
. Khononov V. Learning Domain-Driven Design. O'Reilly Media Inc, 2021.
. https://enterprisecraftsmanship.com/[Khorikov V. Enterprise Craftsmanship].

