= Черновик БЗ проекта
1.0, 03/VII-2025
:source-highliter: rouge
:toc:
:toc-title: Содержание

В данном документе будут описаны предметная область, роли, требования.

== Контекст
При проектировании и реализации доменного уровня в разработке ПО в парадигме _DDD_ требуется обеспечить выполнение и соблюдение ряда условий, принципов и норм, что требует соответствующей метолологии и инструментов. Полагается, что имеется концептуальная модель предметной области, выраженная в виде замысла, текста, диаграмм или кода, как _Proof of Concept_ (PoC), на основе которой необходимо создать кодовую базу доменного уровня целевой предметной области. Данный проект предлагает фреймворк для решения этой задачи.

== О проекте

=== Название
Рабочее название: Kotlin DDD (KDDD)

=== Предмет
Разработка доменных моделей целевой предметной области (ЦПО) на языке Котлин согласно тактическим _DDD-паттернам_ и заданным нормам и ограничениям.

=== Субъект
Разработчик кодовой базы. Организационно-техническая система (ОТС).

== Анализ
В результате анализа формируются *стейкхолдеры*?, *роли*, *бизнес-процессы*, *терминология* (_Ubiquitous Language_).

=== Роли
Роли могут выполняться как человеком, так и программой.

==== Проектировщик
Субъект, разрабатывающий абстракции ЦПО.

==== Имплементатор
Субъект, реализующий имплементации абстракций ЦПО.

==== Интерпретатор
Субъект, выполняющий бизнес-логику.

=== Бизнес-процесс

1. Создать интерфейсы типов, отражающую концепцию по регламенту
2. Создать бизнес-логику
3. Скомпилировать
4. Написать юнит-тесты
5. Создать реализацию интерфейсов
// подъэтапы -- настройки процессора

=== Бизнес-требования

== Анализ
Предмет анализа: разработка кодовой базы, моделирующую целевую предметную область.

Что дано: концепция, идея

// БТ / хотелки
Каким образом (ToBe, образ будущего): DDD, api/impl, ФСТ, FP, FSM, https://github.com/graninas/functional-declarative-design-methodology[FDD]
генерировать все это

//TODO: Определить процессы, роли и данные
// БП
=== Этапы
1. Создать интерфейсы типов, отражающую концепцию по регламенту
2. Создать бизнес-логику
3. Скомпилировать
4. Написать юнит-тесты
5. Создать реализацию интерфейсов
// подъэтапы -- настройки процессора

Результат (что на выходе): данная БЗ: ubiquitous lang, регламенты, БП, БТ, Use Cases, функционал (ТЗ, задачи)



[glossary]
== Термины и определения
[#domain-model]
МПО:: Модель Предметной Области (Domain Model) — совокупность типов данных и их функционала. https://martinfowler.com/eaaCatalog/domainModel.html[Определение по М. Фаулеру].
[#user]
Пользователь:: Разработчик (бизнес-аналитик, архитектор), использующий данную библиотеку для проектирования собственных типов (*CDT*) для некоторого своего домена.
[#fst]
ФСТ:: Формальная система типов, построенная на заданной аксиоматике — постулатах, определяющих допустимые границы значений и операции над типами.
[#pt]
ПТ:: Примитивный тип Котлин: `String`, `Int`, `Boolean`, и т.д.
[#ct]
ТОН:: Тип общего назначения из стандартных пакетов Java и Котлин, не требующих подключения специальных зависимостей: `File`, `UUID`, `URI`, и т.д.
[#fts]
Fts:: Корневой тип библиотеки [k3dm].
[#cdt]
CDT:: Customer Domain Type — проектируемый *Пользователем* собственный тип структуры данных.

