= Заметки к будущей статье о DDD
Tepex <tepex@mail.ru>
1.0, 14/XII-2024
:source-highliter: rouge

Наброс мыслей, тезисов, ссылок и цитат.

== Содержимое

=== 14/XII-2024 21:16
Еще один холивар "говнокод ради интересов бизнеса" vs "НИОКР". Что характерно, вырос из вполне нейтрального новостного поста о DDD и новом блоге Вон Вернона.
https://t.me/c/1304614627/26977[Начало поста]. Холивар идет следом. Лайкнул https://t.me/c/1304614627/26991[этот пост].

=== 17/XII-2024 04:10
Закон Седова

=== 17/XII-2024 20:16
Проектируя доменную модель — проектируешь свой строго ограниченный мир своих типов и правил.
Это значительная часть бизнес-логики. Мы делегируем задачу юнит-тестирования компилятору и IDE.


== Тезисы

=== Что осуществляет:
Фреймворк "KDDD" — это инструмент для разработки ПО на языке Котлин по методикам Domain-Driven-Design (DDD).
Он позволяет:
- В несколько раз сократить затраты на разработку, поддержку и развитие ПО.
- Бюджет разработки.
- Перейти на новый технологический уровень разработки ПО по концепции DDD.

DDD сущесвенно сокращает жизненный цикл поддержки и развития ПО, делает его адаптивным к изменениям окружающей среды. Это дает конкурентное преимущество бизнесу, использующему такое ПО как свое средство производства.

Переход на такой технологический уровень затруднен необходимостью написания большого количества рутинного кода и последующего его изменения при возникновении новых бизнес-требований. Это сильно замедляет разработку и увеличивает количество ошибок. Существуют данные, что 90% времени разработчик тратит не на написание кода, а на его чтение!

Фреймворк "KDDD" решает эту проблему:
- системным подходом при проектировании бизнес-моделей,
- автоматической генерацией соответствующих моделей нижестоящих уровней.
