= Тезаурус
Tepex <tepex@mail.ru>
1.0, 7/VI-2025

В данном документе определяются используемые в проекте *Kddd* понятия, термины и определения. Они не претендуют на всеобщность, могут отличаться от общепринятых и имеют значение в рамках данного проекта и его документации. Список составлен по принципу от общего (абстрактного) к частному (конкретному). Отношения между элементами списка понимаются как: «содержится в», «отражает», «моделирует».

[glossary]
== Понятия, термины и определения
[#subject-area]
Предметная область:: Определение не дается по причине слишком большой широты и абстрактности и по причине того, что это понятие является внешним относительно данного проекта.
[#dimain]
Домен:: Категория программной инженерии, отражающая определенную <<subject-area,*Предметную область*>> путем моделирования для воплощения в виде программного кода. Представляет из себя область знаний и концептуальных моделей и состоит из:
- именований;
- структур данных;
- функционала;
- процессов;
- правил и ограничений;



МПО:: Модель Предметной Области (Domain Model) — совокупность типов данных и их функционала. https://martinfowler.com/eaaCatalog/domainModel.html[Определение по М. Фаулеру].
[#user]
Пользователь:: Разработчик (бизнес-аналитик, архитектор), использующий данную библиотеку для проектирования собственных типов (*CDT*) для некоторого своего домена.
[#fst]
ФСТ:: Формальная система типов, построенная на заданной аксиоматике — постулатах, определяющих допустимые границы значений и операции над типами.
[#pt]
ПТ:: Примитивный тип Котлин: `String`, `Int`, `Boolean`, и т.д.
[#ct]
ТОН:: Тип общего назначения из стандартных пакетов Java и Котлин, не требующих подключения специальных зависимостей: `File`, `UUID`, `URI`, и т.д.
[#kddd]
Kddd:: Корневой тип библиотеки `KDDD`.
[#cdt]
CDT:: Customer Domain Type — проектируемый *Пользователем* собственный тип структуры данных.

